### ISSUE TITLE
Progress Tracker

### ISSUE THREAD

**Issue by Kranthi-Guribilli** [Kranthi-Guribilli/Automate-the-Boring-Stuff-With-Python-Solutions#1]
# Progress Tracker
 - [x]   Chapter 3- Functions:
    * - [x] The Collatz Sequence / Input Validation
 - [x]   Chapter 4- Lists:
    * - [x] Comma Code /Character Picture Grid
 - [x]   Chapter 5- Dictionaries and Structuring Data:
    * - [x] Fantasy Game Inventory / List to Dictionary Function for Game Inventory
 - [x]   Chapter 6- Manipulating Strings:
    * - [x] Table Printer
 - [ ]   Chapter 7- Pattern Matching with Regular Expressions:
    * - [x] Strong Password Detection
    * - [ ] Regex Version of Strip()
 - [ ]   Chapter 8- Reading and Writing Files:
    * - [ ] Extending the Multiclipboard
    * - [ ] Mad Libs
    * - [ ] Regex Search
 - [ ]   Chapter 9- Organizing Files:
    * - [ ] Selective Copy
    * - [ ] Deleting Unneeded Files
    * - [ ] Filling in the Gaps
 - [ ] Chapter 10 - Debugging:
    * - [ ] Debugging Coin Toss
- [ ] Chapter 11 - Web Scraping:
   * - [ ] Command Line Emailer
   * - [ ] Image Site Downloader
   * - [ ] 2048
   * - [ ] Link Verification
- [ ] Chapter 12 - Working with Excel Spreadsheets:
   *  - [ ] Multiplication Table Maker
   *  - [ ] Blank Row Inserter
   *  - [ ] Spreadsheet Cell Inverter
   *  - [ ] Text Files to Spreadsheet
   *  - [ ] Spreadsheet to Text Files
- [ ] Chapter 13 - Working with PDF and Word Documents:
   * - [ ] PDF Paranoia - Encryption
   * - [ ] PDF Paranoia - Decryption
   * - [ ] Custom Invitations as Word Documents
   * - [ ] Brute-Force PDF Password Breaker
- [ ] Chapter 14 - Working with CSV Files and JSON Data:
   * - [ ] Excel-to-CSV Converter
- [ ] Chapter 15 - Keeping Time, Scheduling Tasks, and Launching Programs:
   * - [ ] Prettified Stopwatch
   * - [ ] Scheduled Web Comic Downloader
- [ ] Chapter 16 - Sending Email and Text Messages:
   * - [ ] Random Chore Assignment Emailer
   * - [ ] Umbrella Reminder
   * - [ ] Auto Unsubscriber
   * - [ ] Controlling Your Computer Through Email
- [ ] Chapter 17 - Manipulating Images:
   * - [ ] Extending and Fixing the Chapter Project Programs
   * - [ ] Identifying Photo Folders on the Hard Drive
   * - [ ] Custom Seating Cards
- [ ] Chapter 18 - Controlling the Keyboard and Mouse with GUI Automation:
   * - [ ] Looking Busy
   * - [ ] Instant Messenger Bot
